// ---------------------------------------------------------------------------
// All editable site content lives here. Add a blog post, tweak a lesson,
// change an accent color — you never need to touch App.jsx for content edits.
// ---------------------------------------------------------------------------

export const ROADMAPS = {
  cybersecurity: {
    title: 'Cybersecurity Fundamentals',
    subtitle: 'From security basics to hardening a real app',
    accent: '#4338CA',
    iconName: 'Shield',
    nodes: [
      { id: 1, title: 'Security Mindset 101', desc: 'Threat modeling: assets, actors, attack surfaces.',
        content: [
          'Every security decision starts with the same question: what are you actually protecting, and from whom? An asset is anything worth protecting — data, credentials, uptime, reputation. A threat actor is anyone motivated to go after it, from an opportunistic script kiddie to a targeted attacker.',
          'Threat modeling just means mapping assets to the actors who might want them and the paths they would take to get there. Do this before writing a line of defensive code, and the rest of a security roadmap starts making sense as answers to specific threats instead of a checklist.',
        ] },
      { id: 2, title: 'Password & Auth Hygiene', desc: 'Hashing, salting, MFA — and why weak reuse fails.',
        content: [
          'Passwords should never be stored in plain text. A hash function turns a password into a fixed-length string that can’t be reversed, and a unique salt per user stops attackers from precomputing rainbow tables against your whole user base at once.',
          'Even a perfectly hashed password fails the moment a user reuses it on a site that gets breached. Multi-factor authentication (MFA) is the practical fix: even a leaked password is useless without the second factor, whether that’s a code, a key, or a push approval.',
        ] },
      { id: 3, title: 'Network Fundamentals', desc: 'TCP/IP, firewalls, and how traffic actually moves.',
        content: [
          'Most attacks travel over the same protocols that carry ordinary traffic. Understanding how TCP/IP establishes a connection, and how a firewall decides what to let through based on ports and rules, is what lets you read a security alert and know if it’s real.',
          'A firewall is a filter, not a fortress — it only blocks what it’s configured to block. Combined with network segmentation (keeping sensitive systems on their own isolated network segment), it turns "one breach" into "one contained incident."',
        ] },
      { id: 4, title: 'OWASP Top 10 Overview', desc: 'The most common web app vulnerability classes.',
        content: [
          'The OWASP Top 10 is a community-maintained list of the web vulnerability categories that show up again and again in real breaches — broken access control, injection, cryptographic failures, and more. It’s less a rulebook than a map of where bugs actually live.',
          'Treat it as a checklist to run against your own app: for each category, ask "could this happen here, and how would I know?" That question alone catches more real bugs than most automated scanners.',
        ] },
      { id: 5, title: 'SQL Injection & Input Validation', desc: 'How injection happens, and how parameterized queries stop it.',
        content: [
          'SQL injection happens when user input gets concatenated directly into a database query instead of being treated as pure data. If a form field’s contents can change the structure of the query being run, an attacker can read, modify, or delete data they were never meant to touch.',
          'The fix isn’t "sanitize the input harder" — it’s parameterized queries (prepared statements), which keep user input in a data slot the database engine can never interpret as code. Paired with least-privilege database accounts, this closes the door almost entirely.',
        ] },
      { id: 6, title: 'Cross-Site Scripting (XSS)', desc: 'Stored vs reflected XSS, and safe output encoding.',
        content: [
          'XSS happens when untrusted input gets rendered back into a page as executable script instead of inert text. Reflected XSS bounces off a single request (like a malicious search query); stored XSS is worse — the payload sits in your database and fires for every visitor who views it.',
          'The core defense is output encoding: escape user content for the context it’s rendered in (HTML, attribute, JS) so a browser can never mistake data for code. Modern frameworks do this by default — the risk shows up when a developer opts out for "just this one field."',
        ] },
      { id: 7, title: 'Social Engineering & Phishing', desc: 'Spotting pretexting, spoofed domains, urgency tricks.',
        content: [
          'The weakest link in most breaches isn’t a firewall — it’s a person under time pressure. Social engineering exploits trust and urgency: a fake invoice, a spoofed IT request, a "your account will be locked in 10 minutes" email designed to short-circuit careful thinking.',
          'The tell is almost always a mismatch: a sender domain that’s close but not quite right, a request that skips normal process, or urgency that discourages verification. Slowing down and verifying through a separate channel defeats the vast majority of these attempts.',
        ] },
      { id: 8, title: 'Incident Response Basics', desc: 'Contain, eradicate, recover — the first-hour checklist.',
        content: [
          'When something goes wrong, the instinct to immediately fix everything is usually the wrong one. The first move is containment: stop the bleeding without destroying evidence you’ll need to understand what happened.',
          'From there, the standard flow is eradicate (remove the actual cause), recover (restore normal operation), and review (a blameless retrospective on what let it happen and how to close that gap). Having this order memorized before an incident is what keeps a bad day from becoming a bad month.',
        ] },
      { id: 9, title: 'Capstone: Harden a Sample App', desc: 'Apply it all to lock down a deliberately vulnerable demo.', capstone: true,
        content: [
          'This is where the previous eight lessons stop being theory. Take a small, deliberately vulnerable sample app and work through it end to end: fix the injection points, add MFA, encode output correctly, and segment anything sensitive.',
          'Document what you changed and why for each fix — that write-up is the actual skill. Anyone can patch a known bug; being able to explain the underlying vulnerability class is what transfers to the next app you work on.',
        ] },
    ],
  },
  ai: {
    title: 'AI & Machine Learning',
    subtitle: 'From prompting basics to shipping an AI feature',
    accent: '#7C3AED',
    iconName: 'Brain',
    nodes: [
      { id: 1, title: 'What LLMs Actually Do', desc: 'Tokens, context windows, and why models hallucinate.',
        content: [
          'A large language model doesn’t "know" facts the way a database does — it predicts the most likely next token based on patterns learned from training data. That’s powerful for language tasks, but it explains why a model can state something false with total confidence: it’s optimizing for plausible text, not verified truth.',
          'The context window is everything the model can "see" at once — your prompt plus its own prior output. Once something falls outside that window, the model has no memory of it unless you put it back in.',
        ] },
      { id: 2, title: 'Prompting Fundamentals', desc: 'Clear instructions, examples, and structured output.',
        content: [
          'The biggest lever in prompting is specificity. "Write about dogs" gives the model almost nothing to work with; "write a 100-word product description for a dog harness, aimed at first-time owners" gives it a target to hit.',
          'Examples do more work than most people expect — showing the model one or two examples of the exact output format you want (few-shot prompting) reliably outperforms describing the format in prose.',
        ] },
      { id: 3, title: 'Retrieval-Augmented Generation', desc: 'Grounding responses in your own documents.',
        content: [
          'RAG solves a simple problem: a model’s training data is frozen and doesn’t include your private documents. Instead of retraining the model, RAG retrieves the most relevant chunks of your own data at query time and hands them to the model as context.',
          'The quality of a RAG system lives or dies on retrieval, not generation — if the wrong chunks get pulled in, no amount of prompting fixes a model answering from the wrong source material.',
        ] },
      { id: 4, title: 'Tool Use & Agents', desc: 'Letting a model call functions and take actions.',
        content: [
          'Tool use lets a model go beyond generating text — it can call a defined function (search the web, query a database, send an email) and use the result to inform its next step. This is what turns a chatbot into something that can actually get things done.',
          'An "agent" is just a model given tools and allowed to loop: plan, call a tool, observe the result, decide the next step. The design challenge is less about the model and more about which actions you’re comfortable letting it take without a human checking first.',
        ] },
      { id: 5, title: 'Evaluating Model Output', desc: 'Building test sets so quality is measurable.',
        content: [
          'Without a test set, "did that prompt change help?" is just a feeling. A good eval set is a fixed collection of realistic inputs with either a known correct answer or clear grading criteria, run consistently every time you change a prompt or model.',
          'Start small — even 20 well-chosen examples covering your trickiest edge cases beats a vague sense that "it seems better." Track results over time so regressions are visible instead of anecdotal.',
        ] },
      { id: 6, title: 'Capstone: Ship an AI Feature', desc: 'Wire a model into a real product flow.', capstone: true,
        content: [
          'Pick one real, bounded task — summarizing support tickets, drafting email replies, tagging content — and wire a model into that single flow end to end, including error handling for when the model output is empty, malformed, or wrong.',
          'Ship it behind a feature flag, watch real usage, and keep the eval set from the previous lesson running against it. The gap between a demo and a shipped feature is almost entirely in that unglamorous edge-case handling.',
        ] },
    ],
  },
  design: {
    title: 'Graphic Design Essentials',
    subtitle: 'From color theory to a portfolio-ready piece',
    accent: '#D97706',
    iconName: 'Palette',
    nodes: [
      { id: 1, title: 'Color Theory Basics', desc: 'Contrast, harmony, and building a palette that works.',
        content: [
          'Color isn’t decoration — it’s the fastest signal a design sends. Contrast is what makes text readable and elements distinguishable; harmony is what keeps a palette from feeling random. Most working palettes are built from 4–6 colors: a dominant, a couple of supporting tones, and one accent used sparingly.',
          'Pick your accent last, not first. Nail the neutral base of a palette before deciding what single color gets to demand attention — an accent only works because everything around it is quiet.',
        ] },
      { id: 2, title: 'Typography Foundations', desc: 'Pairing typefaces and setting a real type scale.',
        content: [
          'Two typefaces is usually the right number: a display face with personality for headlines, used sparingly, and a highly legible body face for everything else. Pairing the same family for both roles almost always reads as safe rather than intentional.',
          'A type scale is a fixed set of sizes (not arbitrary pixel values chosen per element) that keeps a layout consistent. Once you’ve set one, every heading and paragraph pulls from it instead of being eyeballed.',
        ] },
      { id: 3, title: 'Layout & Grid Systems', desc: 'Structuring a page so the eye knows where to go.',
        content: [
          'A grid is an invisible structure that aligns elements so a layout feels deliberate instead of scattered. It doesn’t need to be rigid — breaking the grid on purpose for one element is a common way to create emphasis, but only once the reader has learned what "normal" looks like.',
          'Whitespace is part of the grid, not what’s left over after placing content. Generous spacing around a focal element is often what makes it feel important, more than size or color does.',
        ] },
      { id: 4, title: 'Branding & Identity', desc: 'Logos, marks, and consistent visual voice.',
        content: [
          'A brand identity is a system, not a logo. The mark matters, but what makes an identity recognizable across contexts is the consistent use of the same palette, type, and tone of voice everywhere the brand shows up.',
          'Design for the smallest and most awkward use case first — a favicon, a business card, a single-color print job. A mark that survives those constraints will look even better everywhere else.',
        ] },
      { id: 5, title: 'Capstone: Design a Brand Kit', desc: 'Ship a small, cohesive identity system.', capstone: true,
        content: [
          'Put it together: a logo mark, a 4–6 color palette, a type pairing, and 3–4 example applications (business card, social post, simple webpage). The goal isn’t volume — it’s proving the system holds together across different formats.',
          'Write one sentence describing who this brand is for and what it should feel like before you touch color or type. Every choice after that should trace back to that sentence.',
        ] },
    ],
  },
  tools: {
    title: 'Tools & Productivity Tips',
    subtitle: 'The workflow shortcuts that actually save time',
    accent: '#059669',
    iconName: 'Wrench',
    nodes: [
      { id: 1, title: 'Keyboard-First Workflows', desc: 'Cutting mouse trips out of your daily routine.',
        content: [
          'Every trip to the mouse and back costs a fraction of a second of focus, and it adds up over a full day. Learning the handful of keyboard shortcuts you use constantly — window switching, search, common app actions — pays for itself within a week.',
          'Don’t try to learn twenty shortcuts at once. Pick the three actions you repeat most often today, learn those, and let the rest come naturally as friction shows up.',
        ] },
      { id: 2, title: 'Automation Basics', desc: 'When a script beats a repeated manual task.',
        content: [
          'Not everything repeated is worth automating — a rough rule of thumb is: if a task takes under a minute and happens rarely, doing it by hand is fine. If it happens daily or the steps are error-prone, that’s a signal to script it.',
          'Start with the smallest possible automation, even a five-line script, rather than trying to build the perfect general tool. A working shortcut you actually use beats a polished one you never finish.',
        ] },
      { id: 3, title: 'Version Control Habits', desc: 'Commits, branches, and not fearing git.',
        content: [
          'A commit is a checkpoint, not a formality. Small, frequent commits with a clear message ("fix login redirect bug" beats "updates") make it possible to find exactly when and why something changed, months later.',
          'Branches exist so you can experiment without risking working code. Treat your main branch as always deployable, and do anything uncertain on a separate branch you can throw away if it doesn’t work out.',
        ] },
      { id: 4, title: 'Capstone: Automate a Chore', desc: 'Build one real automation you’ll keep using.', capstone: true,
        content: [
          'Find one task you actually do every week — renaming files, formatting a report, backing something up — and automate exactly that, nothing more. The best capstone here is boring: something you’ll genuinely keep running.',
          'Once it works, spend five minutes writing down what it does and why, in plain language. Future-you (or a teammate) will thank present-you the first time it breaks.',
        ] },
    ],
  },
};

export const BLOG_POSTS = [
  { id: 1, cat: 'Cybersecurity', accent: '#4338CA', title: 'SQL Injection, Explained Without the Jargon',
    excerpt: 'What actually happens when input isn’t sanitized, and why parameterized queries fix it for good.',
    author: 'Philemon', readTime: '7 min read', date: 'Jul 12, 2026',
    image: 'https://images.unsplash.com/photo-1620825937374-87fc7d6bddc2?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'KeepCoding', profileUrl: 'https://unsplash.com/@keepcoding_school', photoUrl: 'https://unsplash.com/photos/man-in-black-jacket-using-computer-lVF2HLzjopw' },
    content: [
      'Picture a login form that builds a database query by gluing your username straight into a string. Under normal use, that’s invisible — the username slots in, the query runs, everyone moves on. The problem shows up the moment someone types something that isn’t just a username.',
      'If an attacker enters a value that includes database syntax, and that value gets concatenated directly into the query, the database can’t tell the difference between "data" and "instructions." A classic example is typing something like `admin\' --` into a username field: the apostrophe closes the intended string early, and everything after the double-dash gets treated as a comment, silently deleting the rest of the query — including the password check.',
      'This isn’t a theoretical bug. SQL injection has been on the OWASP Top 10 list of web vulnerabilities for over a decade, and it has been at the root of some of the largest data breaches on record, from exposed customer databases to full administrative takeovers. The reason it persists is simple: it\'s easy to write vulnerable code without realizing it, especially when a query is built with basic string concatenation instead of a safer alternative.',
      'The fix is parameterized queries, also called prepared statements. Instead of building a query as one string and hoping the input behaves, you define the query structure separately from the values, and hand the values to the database driver as data — never as code the database has to interpret. The database engine keeps the two completely separate at the protocol level, so no amount of clever quoting in the input can change what the query does.',
      'Every mainstream database library supports this: `cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))` in Python, prepared statements in Java\'s JDBC, parameterized queries in .NET\'s ADO — the pattern is universal even when the syntax differs. Input validation (checking that an email field looks like an email, that an ID is numeric) is still worth doing as a second layer, but it should never be the only defense, because it\'s trying to predict every malicious pattern in advance rather than removing the vulnerability at its source.',
      'If you\'re auditing an existing codebase, the fastest way to find risk is to search for string concatenation or f-strings feeding directly into a query call. Any hit there is worth a closer look — and worth fixing before it becomes the subject of someone else\'s writeup.',
    ],
    takeaways: [
      'SQL injection happens when user input can change the structure of a query, not just its data.',
      'Parameterized queries separate query structure from values at the database driver level — this is the real fix.',
      'Input validation is a useful second layer, but it should never be the only defense.',
      'Audit existing code by searching for string concatenation feeding directly into database calls.',
    ] },
  { id: 2, cat: 'Cybersecurity', accent: '#4338CA', title: 'Phishing Emails: The Five Tells',
    excerpt: 'Domain spoofing, urgency language, and other patterns worth training your eye on.',
    author: 'Philemon', readTime: '6 min read', date: 'Jul 8, 2026',
    image: 'https://images.unsplash.com/photo-1620825937374-87fc7d6bddc2?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'KeepCoding', profileUrl: 'https://unsplash.com/@keepcoding_school', photoUrl: 'https://unsplash.com/photos/man-in-black-jacket-using-computer-lVF2HLzjopw' },
    content: [
      'Most phishing emails aren’t sophisticated — they rely on you reading fast, on a busy morning, on a phone screen, and not checking closely. A handful of patterns show up again and again across almost every campaign, and once you\'ve trained your eye to catch them, they become obvious even at a glance.',
      'The first tell is the sender domain. A lookalike domain like "micros0ft-support.com" or "paypal-secure-verify.net" banks entirely on you not reading closely — the brand name is right there, so the email feels legitimate on a skim. The second is artificial urgency: "act within 24 hours or your account will be permanently locked" is engineered specifically to make you skip verification and act on impulse instead of checking calmly.',
      'The third tell is a generic greeting on an email that claims to be personal or time-sensitive — "Dear valued customer" from a bank that supposedly has your account details doesn\'t add up. The fourth is a mismatch between the display name and the actual email address; most email clients let you tap or hover on the sender name to reveal the real address underneath, and that\'s often where the disguise falls apart. The fifth is a link where the visible text doesn\'t match where it actually points — hovering over a link (or long-pressing on mobile) shows the real destination before you commit to clicking it.',
      'Modern phishing has also gotten more targeted. "Spear phishing" uses information about you specifically — your employer, a colleague\'s name, a recent purchase — to make the generic tricks above feel personal and therefore more convincing. The underlying tells are usually still there; they\'re just wrapped in more convincing packaging.',
      'The single most reliable defense isn\'t vigilance, because vigilance runs out on a tired Tuesday afternoon. It\'s process: never act on a request for credentials, payment, or sensitive information by clicking through the email itself, no matter how urgent it looks. Open a new browser tab and navigate to the real site directly, or contact the person or company through a phone number or channel you already had — never one provided in the suspicious message itself.',
      'If you run a team, the highest-leverage thing you can do isn\'t a one-time training session — it\'s making it socially normal to report a suspicious email and ask "is this real?" without anyone feeling foolish for asking.',
    ],
    takeaways: [
      'Check the actual sender domain, not just the display name — lookalike domains are the most common trick.',
      'Urgency language is a manipulation tactic, not a reason to skip verification.',
      'Hover or long-press links to see the real destination before clicking.',
      'Verify requests for sensitive info through a channel you already trust, never one the message provides.',
    ] },
  { id: 3, cat: 'AI & ML', accent: '#7C3AED', title: 'Prompting Like You Mean It',
    excerpt: 'Structure, examples, and constraints — the three levers that actually move output quality.',
    author: 'Philemon', readTime: '8 min read', date: 'Jul 15, 2026',
    image: 'https://images.unsplash.com/photo-1697577418970-95d99b5a55cf?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Igor Omilaev', profileUrl: 'https://unsplash.com/@omilaev', photoUrl: 'https://unsplash.com/photos/a-computer-chip-with-the-letter-a-on-top-of-it-eGGFZ5X2LnA' },
    content: [
      'Most disappointing model output traces back to an underspecified prompt, not a weak model. It\'s tempting to blame the AI when a result feels generic or misses the point, but in the overwhelming majority of cases the model did exactly what it was asked — the ask just wasn\'t specific enough to produce something useful.',
      'Three changes consistently move output quality more than anything else: adding structure, adding examples, and adding explicit constraints. Structure means telling the model the shape of what you want — headings, a specific order, a target length — rather than describing the topic in prose and hoping the format works out. "Write about our product" invites a generic essay; "write three bullet points, each under 15 words, highlighting a different customer benefit" gives the model an actual target to hit.',
      'Examples do more work than most people expect. Showing the model one or two instances of the exact output format you want — what\'s often called few-shot prompting — reliably outperforms describing that same format in a paragraph of instructions. If you want a specific tone, a specific structure, or a specific level of technical depth, showing beats telling almost every time.',
      'Constraints close off the wrong answers before they happen. "Don\'t use technical jargon," "keep it under 100 words," or "don\'t mention competitors by name" each remove an entire category of unwanted output rather than hoping the model infers your preferences. The more specific the constraint, the less room there is for the model to wander somewhere unhelpful.',
      'It also helps to give the model room to think before it answers, especially for anything involving reasoning or multi-step logic — asking it to work through the problem step by step before giving a final answer measurably improves accuracy on harder tasks, because it gives the model a chance to catch its own mistakes mid-thought rather than committing to the first plausible-sounding response.',
      'The habit worth building is treating your first prompt as a draft, not a final attempt. Read the output, notice specifically what\'s wrong — too long, wrong tone, missed a requirement — and fix the prompt itself, not just the output by hand. That way the next generation (and the one after that) doesn\'t repeat the same mistake, and over time you end up with a reusable prompt instead of a one-off patch job.',
    ],
    takeaways: [
      'Vague prompts produce vague output — specificity is the single biggest lever you control.',
      'Show the model an example of the format you want rather than only describing it.',
      'Explicit constraints ("under 100 words," "no jargon") remove entire categories of bad output.',
      'Treat your first prompt as a draft: fix the prompt itself when the output misses, not just the result.',
    ] },
  { id: 4, cat: 'AI & ML', accent: '#7C3AED', title: 'RAG in Plain English',
    excerpt: 'How retrieval-augmented generation keeps a model grounded in your own data.',
    author: 'Philemon', readTime: '7 min read', date: 'Jul 3, 2026',
    image: 'https://images.unsplash.com/photo-1697577418970-95d99b5a55cf?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Igor Omilaev', profileUrl: 'https://unsplash.com/@omilaev', photoUrl: 'https://unsplash.com/photos/a-computer-chip-with-the-letter-a-on-top-of-it-eGGFZ5X2LnA' },
    content: [
      'A language model only knows what it saw during training, frozen at a specific point in time. That means it knows nothing about your internal documents, your product\'s latest changes, last week\'s support tickets, or anything written after its training cutoff — no matter how confidently it might guess. Retrieval-augmented generation, almost always shortened to RAG, works around that limitation without retraining or fine-tuning the underlying model at all.',
      'The mechanism is more straightforward than the name suggests. At query time, a RAG system takes the user\'s question, searches your own document collection for the chunks of text most relevant to it — usually via a technique called vector search, which finds passages that are semantically similar even if they don\'t share exact keywords — and hands those chunks to the model as extra context alongside the original question. The model then answers using what it was just given, rather than reaching into its own frozen training data and guessing.',
      'This is why RAG has become the default approach for building an internal "chat with our docs" tool, a customer support assistant that knows your actual product, or any system where accuracy against a specific source of truth matters more than general knowledge. It\'s dramatically cheaper and faster than fine-tuning a model, and critically, it keeps answers traceable — a good RAG system can show you exactly which document a given answer came from.',
      'The part that actually determines quality is retrieval, not generation. If the search step pulls in the wrong document chunks — because the documents weren\'t split into sensible sections, or the search algorithm missed the relevant passage — the model will confidently answer from the wrong material, and no amount of prompt engineering downstream fixes that. This is why most real-world RAG debugging time goes into improving how documents are chunked and searched, not into tweaking the final prompt.',
      'A few practical details matter more than they might seem: chunk size (too small loses context, too large dilutes relevance), overlap between chunks (so a fact split across a chunk boundary doesn\'t get lost), and re-ranking retrieved results before handing them to the model (a cheap way to filter out near-misses that technically matched but aren\'t actually useful).',
      'If you\'re evaluating whether a RAG system is working well, the fastest diagnostic isn\'t "does the answer sound right" — it\'s "did it retrieve the right source material in the first place." Fix retrieval first; everything downstream gets easier once the model is looking at the right information.',
    ],
    takeaways: [
      'RAG grounds a model in your own data at query time, without retraining it.',
      'The core mechanism: search your documents for relevant chunks, then hand those to the model as context.',
      'Retrieval quality determines overall quality — a wrong chunk means a confidently wrong answer.',
      'Chunk size, overlap, and re-ranking are the practical levers worth tuning first.',
    ] },
  { id: 5, cat: 'Graphic Design', accent: '#D97706', title: 'Picking a Palette That Isn’t Generic',
    excerpt: 'A quick framework for choosing 4–6 colors that actually say something.',
    author: 'Philemon', readTime: '6 min read', date: 'Jun 29, 2026',
    image: 'https://images.unsplash.com/photo-1716471330475-f0669db8947a?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Andy Brown', profileUrl: 'https://unsplash.com/@basallt', photoUrl: 'https://unsplash.com/photos/a-circle-of-color-swatches-on-a-white-surface-9bC6YPVk0Ts' },
    content: [
      'A lot of palettes end up generic because they\'re chosen backwards: pick a pretty accent color first — usually whatever\'s trending that year — then build neutrals around it as an afterthought. The result usually looks like every other product using the same trending color, because the accent was chosen for how it looks in isolation, not for what it needs to do inside a real interface or layout.',
      'Try the opposite order. Nail your neutrals first — a background color, a primary text color, and two or three grays for borders, secondary text, and disabled states — and get those feeling right entirely on their own, with no accent color anywhere in sight. A palette of pure neutrals should already look calm and intentional before you add a single splash of color. Only once that foundation holds up should you choose an accent, and choose it for a specific reason tied to what you\'re designing — a fintech app might reach for a trustworthy blue, a creative tool for something more energetic — rather than because it\'s currently popular on design Twitter.',
      'Limit yourself to one true accent color used sparingly, reserved for the actions and elements that genuinely need attention: a primary button, an active state, a key data point in a chart. If everything is emphasized, nothing is — an accent color only reads as important because the vast majority of the interface deliberately isn\'t using it.',
      'Contrast ratio matters more than most people budget time for. Text needs to meet accessibility contrast minimums against its background (WCAG recommends at least 4.5:1 for normal body text), and it\'s worth checking this with an actual contrast checker rather than eyeballing it, since colors that look readable on a bright monitor can fail badly for users with low vision or in bright sunlight on mobile.',
      'A genuinely useful test before finalizing any palette: convert your whole design to grayscale and see if it still holds together. If the hierarchy collapses the moment color is removed — if you can no longer tell what\'s a button versus a label versus a heading — the palette was doing work that layout, size, and type weight should have been doing all along. Color should clarify a hierarchy that already exists, not manufacture one that isn\'t there.',
    ],
    takeaways: [
      'Build your neutral palette first and get it right before adding any accent color.',
      'Use one accent color sparingly — reserved for genuinely important actions and states.',
      'Check contrast ratios with a real tool; don\'t eyeball accessibility.',
      'Test in grayscale — if the hierarchy collapses without color, layout and type need work too.',
    ] },
  { id: 6, cat: 'Graphic Design', accent: '#D97706', title: 'Type Pairing 101',
    excerpt: 'How to combine a display face and a body face without it looking accidental.',
    author: 'Philemon', readTime: '6 min read', date: 'Jun 24, 2026',
    image: 'https://images.unsplash.com/photo-1716471330475-f0669db8947a?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Andy Brown', profileUrl: 'https://unsplash.com/@basallt', photoUrl: 'https://unsplash.com/photos/a-circle-of-color-swatches-on-a-white-surface-9bC6YPVk0Ts' },
    content: [
      'Good type pairing usually comes from deliberate contrast, not similarity. Two typefaces that are almost identical in weight and style tend to read as a mistake — as if someone meant to pick one font but accidentally used two — while a characterful display face paired with a plain, highly legible body face reads as intentional, because the difference in role is visually obvious.',
      'A reliable starting point is to choose your body face first, since it carries the overwhelming majority of the text and needs to be comfortable to read at length, in a paragraph, at a normal reading size — not just look nice as a single word in a mockup. Prioritize x-height, letter spacing, and how it holds up at 14–16px on a screen over how distinctive it looks blown up on a slide.',
      'Once the body face is settled, pick a display face for headlines and large text that contrasts in weight or style — a bold geometric sans against a serif body, or a serif display against a clean sans body. The goal is a clear visual signal that "this text is a different kind of thing than that text," which is exactly what a heading needs to communicate at a glance before anyone reads a single word of it.',
      'Limit yourself to two type families for the vast majority of projects, and lean on the tools within each one — weight, size, letter spacing, italics — to create variety instead of reaching for a third typeface. Adding a third family rarely adds personality; it usually just adds visual noise and makes the design feel less considered, not more.',
      'One detail that separates amateur pairing from professional pairing: matching the x-height and overall visual weight roughly between your two chosen faces, even though they\'re different styles. Two fonts that are wildly mismatched in optical size at the same point size will look uneven side by side, even if each one individually looks fine.',
      'When in doubt, a dependable fallback combination is a confident, slightly quirky display face for headlines paired with a neutral, highly-tested workhorse sans for body copy — something like a geometric or humanist sans that\'s been battle-tested at small sizes across screens. It\'s not the most exciting choice, but it almost never looks wrong.',
    ],
    takeaways: [
      'Pair fonts by contrast, not similarity — near-identical typefaces read as a mistake.',
      'Choose your body face first; it carries the most text and needs to be comfortable at reading size.',
      'Stick to two type families and use weight, size, and spacing for variety instead of a third font.',
      'Match the optical/x-height weight between your two chosen faces so they sit well together.',
    ] },
  { id: 7, cat: 'Tools', accent: '#059669', title: 'Automate the Boring 20%',
    excerpt: 'A simple test for deciding when a repeated task is worth scripting.',
    author: 'Philemon', readTime: '5 min read', date: 'Jun 18, 2026',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Christopher Gower', profileUrl: 'https://unsplash.com/@cgower', photoUrl: 'https://unsplash.com/photos/a-macbook-with-lines-of-code-on-its-screen-on-a-busy-desk-m_HRfLhgABo' },
    content: [
      'Not every repeated task deserves a script. Building and maintaining automation has a real, ongoing cost — the time to write it, the time to test it, the time to fix it when the underlying tool or website changes — so it\'s worth a quick, honest gut check before reaching for it: how often does this actually happen, and how error-prone is it when done by hand?',
      'A task that takes thirty seconds and happens once a month almost never pays back the time spent automating it, even if automating it sounds satisfying. Do the math explicitly if you\'re unsure: multiply the manual time saved per occurrence by how often it happens over the next year, and compare that honestly to how long the automation would actually take to build and maintain — including the debugging time you\'re probably underestimating.',
      'A task that takes five minutes, happens daily, and is easy to get slightly wrong — renaming a batch of files consistently, reformatting a recurring report, pulling the same numbers from three different dashboards — is exactly the kind worth scripting. The payback often shows up within the first week, and the error-reduction benefit (a script does the same thing every time; a tired human on a Friday afternoon doesn\'t) is worth almost as much as the time saved.',
      'Start with the smallest possible version, even a five-line script that only handles the common case, rather than trying to design a fully general tool that handles every edge case up front. A working shortcut you actually use and iterate on beats a polished, ambitious tool you never finish building because the scope kept growing before you shipped anything.',
      'It\'s also worth distinguishing automation from optimization. Automation removes a manual step entirely; optimization just makes an existing manual step faster. Both have value, but they\'re different investments — a faster way to do something you do rarely is often not worth building, while a slightly slower automation of something you do constantly usually still wins.',
      'Finally, write down what the script does and why, even briefly, the moment it works — not "eventually." The five minutes it takes to leave a comment or a short README entry is nothing compared to the confusion of finding an unlabeled script six months later and not trusting it enough to run it.',
    ],
    takeaways: [
      'Automate based on frequency × error-proneness, not just "this feels tedious."',
      'A rarely-run 30-second task usually isn\'t worth automating; a daily 5-minute task usually is.',
      'Ship the smallest version that handles the common case rather than building a general tool up front.',
      'Document what a script does the moment it works, before you forget the context.',
    ] },
  { id: 8, cat: 'Tools', accent: '#059669', title: 'Git Habits That Save Future You',
    excerpt: 'Small commit discipline that makes debugging six months from now painless.',
    author: 'Philemon', readTime: '6 min read', date: 'Jun 10, 2026',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    credit: { name: 'Christopher Gower', profileUrl: 'https://unsplash.com/@cgower', photoUrl: 'https://unsplash.com/photos/a-macbook-with-lines-of-code-on-its-screen-on-a-busy-desk-m_HRfLhgABo' },
    content: [
      'A commit history is a message to your future self, and most people write it as an afterthought squeezed in right before pushing. "Fixed stuff" or "updates" tells you nothing six months later when you\'re trying to figure out exactly when a bug was introduced, or why a particular line of code exists at all.',
      'Commit small, logically complete changes — one fix, one feature, one refactor per commit — with a message that explains what changed and, briefly, why. "Fix off-by-one error in pagination count" is specific, searchable, and immediately useful later; "updates" or "wip" is neither, and you\'ll regret it the first time you need to `git blame` your way to an answer under time pressure.',
      'Branches are cheap, and that\'s the whole point of them — use them liberally for anything experimental or uncertain rather than committing directly to your main line of work. Keep your main branch always in a working, deployable state, and do anything you\'re not sure about on a separate branch you can safely abandon if it doesn\'t pan out. This alone prevents the vast majority of "wait, when did this start breaking" investigations, because main never contains half-finished, broken work in the first place.',
      'A habit that pays off disproportionately: writing the commit message before you write the code, as a one-line plan of what you\'re about to do. If you can\'t summarize the change in one clear sentence before starting, that\'s often a sign the change is trying to do two unrelated things and should probably be split into two commits.',
      'When something does go wrong in production, a clean, well-labeled history turns `git bisect` from a guessing game into a fast, almost mechanical search — you can jump straight to the commit that introduced a regression instead of manually testing a dozen candidates. That speed only exists because of the discipline you put in earlier, when nothing was on fire yet.',
      'None of this requires memorizing complex git workflows. Small commits, honest messages, and a main branch that always works will cover the overwhelming majority of situations a team actually runs into — the fancier techniques are worth learning later, once these basics are automatic.',
    ],
    takeaways: [
      'Write specific, searchable commit messages — "fix X because Y," never "updates."',
      'Keep commits small and logically complete: one fix or feature per commit.',
      'Treat main as always-deployable; do uncertain work on a disposable branch.',
      'A clean history turns debugging regressions into a fast search instead of a guessing game.',
    ] },
];
